### PR TITLE
Removed root user dependency, added PAM authentication

### PR DESCRIPTION
**Pull request by tamisoft**
Example PAM file in /etc/pam.d/rttys, to check if the user given is member of
any groups listed in the /etc/rttys/groups.allowed file. Uses SSSD for auth.

auth        requisite      pam_listfile.so onerr=fail item=group sense=allow file=/etc/rttys/groups.allowed
auth        required      pam_sss.so forward_pass

account     [default=bad success=ok user_unknown=ignore] pam_sss.so

### CODE REVIEW

**Comment by zhaojh329** [comment]
Is it compatible with the current login method?

**Comment by tamisoft** [comment]
Since it redirects authentication to the PAM system, it is compatible with the original + allows you to use any authentication methods supported by the OS. You can test it by using a symlink from /etc/pam.d/password-auth -> /etc/pam.d/rttys

**Comment by zhaojh329** [comment]
```
zjh@zjh-GE60-2PL:~/go/src/github.com/zhaojh329/rttys$ ./build.sh 
Generating a RSA private key
.+++++
.......................................................................................................................+++++
writing new private key to 'output/ca.key'
-----
Created CA certificate in output/ca.crt
subject=
    commonName                = An MQTT broker
    organizationName          = OwnTracks.org
    organizationalUnitName    = generate-CA
    emailAddress              = nobody@example.net
Warning: the CA key is not encrypted; store it safely!
--- Creating server key and signing request
Generating RSA private key, 2048 bit long modulus (2 primes)
.........+++++
.........................+++++
e is 65537 (0x010001)
--- Creating and signing server certificate
Signature ok
subject=CN = rttys, O = OwnTracks.org, OU = generate-CA, emailAddress = nobody@example.net
Getting CA Private Key
# github.com/zhaojh329/rttys/pwauth
pwauth/auth_linux.go:10:12: undefined: pam.StartFunc
pwauth/auth_linux.go:10:52: undefined: pam.Style
pwauth/auth_linux.go:12:8: undefined: pam.PromptEchoOff
pwauth/auth_linux.go:14:8: undefined: pam.PromptEchoOn
pwauth/auth_linux.go:16:8: undefined: pam.ErrorMsg
pwauth/auth_linux.go:19:8: undefined: pam.TextInfo
rttys-linux-amd64/
rttys-linux-amd64/rttys.crt
rttys-linux-amd64/rttys.key
rttys-linux-amd64/rttys.conf
# github.com/zhaojh329/rttys/pwauth
pwauth/auth_linux.go:10:12: undefined: pam.StartFunc
pwauth/auth_linux.go:10:52: undefined: pam.Style
pwauth/auth_linux.go:12:8: undefined: pam.PromptEchoOff
pwauth/auth_linux.go:14:8: undefined: pam.PromptEchoOn
pwauth/auth_linux.go:16:8: undefined: pam.ErrorMsg
pwauth/auth_linux.go:19:8: undefined: pam.TextInfo
rttys-linux-386/
rttys-linux-386/rttys.crt
rttys-linux-386/rttys.key
rttys-linux-386/rttys.conf
  adding: rttys-windows-amd64/ (stored 0%)
  adding: rttys-windows-amd64/rttys.crt (deflated 35%)
  adding: rttys-windows-amd64/rttys.key (deflated 23%)
  adding: rttys-windows-amd64/rttys.conf (deflated 31%)
  adding: rttys-windows-amd64/rttys.exe (deflated 51%)
  adding: rttys-windows-386/ (stored 0%)
  adding: rttys-windows-386/rttys.crt (deflated 35%)
  adding: rttys-windows-386/rttys.key (deflated 23%)
  adding: rttys-windows-386/rttys.conf (deflated 31%)
  adding: rttys-windows-386/rttys.exe (deflated 46%)
rttys-darwin-amd64/
rttys-darwin-amd64/rttys.crt
rttys-darwin-amd64/rttys
rttys-darwin-amd64/rttys.key
rttys-darwin-amd64/rttys.conf
rttys-darwin-386/
rttys-darwin-386/rttys.crt
rttys-darwin-386/rttys
rttys-darwin-386/rttys.key
rttys-darwin-386/rttys.conf
rttys-freebsd-amd64/
rttys-freebsd-amd64/rttys.crt
rttys-freebsd-amd64/rttys
rttys-freebsd-amd64/rttys.key
rttys-freebsd-amd64/rttys.conf
rttys-freebsd-386/
rttys-freebsd-386/rttys.crt
rttys-freebsd-386/rttys
rttys-freebsd-386/rttys.key
rttys-freebsd-386/rttys.conf
```

**Comment by zhaojh329** [comment]
```
pwauth/auth_linux.go:10:12: undefined: pam.StartFunc
pwauth/auth_linux.go:10:52: undefined: pam.Style
pwauth/auth_linux.go:12:8: undefined: pam.PromptEchoOff
pwauth/auth_linux.go:14:8: undefined: pam.PromptEchoOn
pwauth/auth_linux.go:16:8: undefined: pam.ErrorMsg
pwauth/auth_linux.go:19:8: undefined: pam.TextInfo
```

**Comment by tamisoft** [comment]
Let me check, I used go build in the directory, not the build.sh. Or have you fixed it already?

**Comment by zhaojh329** [comment]
Thus, then cross-platformity is not very friendly.

**Comment by tamisoft** [comment]
It is only the matter of building it for on a different-than-target architecture (kinda cross compiling). There is a pull that modifies the build.sh to be able to build fine as long as the OS has the dev packages.

**Pull request merged**
